version: "2.4"

services:

  web:
    image: nginx
    ports:
      - 8080-8081:8080
    deploy:
      replicas: 2
      restart_policy:
        condition: any


  db:
    image: mongo

  app1:
    image: app1:v1.0
