name: build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push latest to docker.com and ghcr.io
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        env:
          DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
          DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          GH_REGISTRY_USERNAME: ${{ github.actor }}
          GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
        run: |
          version=snapshot
          revision=${GITHUB_SHA:0:7}
          ref_name=${GITHUB_REF#refs/*/}
          echo PUBLISH VERSION: ${version}
          echo ${GH_REGISTRY_TOKEN} | docker login ghcr.io -u ${GH_REGISTRY_USERNAME} --password-stdin
          echo ${DOCKER_REGISTRY_TOKEN} | docker login -u ${DOCKER_REGISTRY_USERNAME} --password-stdin
          docker buildx build --push \
              --build-arg VERSION=${version} --build-arg REVISION=${revision} --build-arg REF_NAME=${ref_name} \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              -t ghcr.io/${GH_REGISTRY_USERNAME}/opener:${version} -t ${DOCKER_REGISTRY_USERNAME}/opener:${version} dockerbuild

      - name: build and push tag and latest to docker.com and ghcr.io
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
          DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          GH_REGISTRY_USERNAME: ${{ github.actor }}
          GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
        run: |
          version=${GITHUB_REF#refs/tags/v}
          revision=${GITHUB_SHA:0:7}
          ref_name=${GITHUB_REF#refs/*/}
          echo PUBLISH VERSION: ${version} latest
          echo ${GH_REGISTRY_TOKEN} | docker login ghcr.io -u ${GH_REGISTRY_USERNAME} --password-stdin
          echo ${DOCKER_REGISTRY_TOKEN} | docker login -u ${DOCKER_REGISTRY_USERNAME} --password-stdin
          docker buildx build --push \
              --build-arg VERSION=${version} --build-arg REVISION=${revision} --build-arg REF_NAME=${ref_name} \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              -t ghcr.io/${GH_REGISTRY_USERNAME}/opener:${version} -t ${DOCKER_REGISTRY_USERNAME}/opener:${version} \
              -t ghcr.io/${GH_REGISTRY_USERNAME}/opener:latest -t ${DOCKER_REGISTRY_USERNAME}/opener:latest dockerbuild
